[package]
name = "app-count"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Count installed applications across native and WOW64 registry views"

[dependencies]
rustbof.workspace = true
common = { path = "../../common" }

[lib]
crate-type = ["staticlib"]
name = "app_count"
