#!/usr/bin/env python3
"""
gen_bof_catalog.py — generate docs/bof-catalog.md from Cargo metadata + source.

Walks every BOF crate, extracts:
  - crate name (from Cargo.toml [package].name)
  - description (from Cargo.toml [package].description)
  - MITRE techniques (from src/lib.rs TECHNIQUES const)
  - aggressor synopsis + args (from aggressor/dani-suite.cna beacon_command_register)

Emits a single Markdown catalog grouped by phase directory.
"""

from __future__ import annotations
import re
import sys
from pathlib import Path
from dataclasses import dataclass, field

ROOT = Path(__file__).resolve().parent.parent
CNA = ROOT / "aggressor" / "dani-suite.cna"
OUT = ROOT / "docs" / "bof-catalog.md"

PHASES = [
    ("situational-awareness", "Situational Awareness"),
    ("remote-ops",            "Remote Operations"),
    ("operators-kit",         "OperatorsKit"),
    ("c2-collection",         "C2-Collection"),
    ("persistence",           "Persistence"),
]

RE_PKG_NAME = re.compile(r'^\s*name\s*=\s*"([^"]+)"', re.M)
RE_PKG_DESC = re.compile(r'^\s*description\s*=\s*"([^"]+)"', re.M)
RE_TECHNIQUE = re.compile(
    r'Technique\s*\{\s*id:\s*"([^"]+)"\s*,\s*name:\s*"([^"]+)"\s*,\s*tactic:\s*"([^"]+)"'
)

# aggressor: alias <name> { ... } followed by beacon_command_register("<name>", "<short>", "<help>")
RE_AGGR = re.compile(
    r'beacon_command_register\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)',
    re.S,
)


@dataclass
class Bof:
    crate: str
    phase: str
    name: str = ""
    desc: str = ""
    techniques: list[tuple[str, str, str]] = field(default_factory=list)
    aggr_short: str = ""
    aggr_args: str = ""


def parse_bof(phase_dir: str, crate_dir: Path) -> Bof | None:
    cargo = crate_dir / "Cargo.toml"
    lib   = crate_dir / "src" / "lib.rs"
    if not cargo.exists() or not lib.exists():
        return None

    bof = Bof(crate=crate_dir.name, phase=phase_dir)
    cargo_text = cargo.read_text(errors="replace")
    if (m := RE_PKG_NAME.search(cargo_text)):
        bof.name = m.group(1)
    if (m := RE_PKG_DESC.search(cargo_text)):
        bof.desc = m.group(1)

    lib_text = lib.read_text(errors="replace")
    bof.techniques = RE_TECHNIQUE.findall(lib_text)
    return bof


def parse_aggressor(cna_path: Path) -> dict[str, tuple[str, str]]:
    """Return {bof_name: (short_desc, help_block_first_line)}."""
    if not cna_path.exists():
        return {}
    text = cna_path.read_text(errors="replace")
    out = {}
    for name, short, helpb in RE_AGGR.findall(text):
        # extract the Args: line if present
        first_args = ""
        for line in helpb.split("\\n"):
            line = line.strip()
            if line.lower().startswith("args:"):
                first_args = line[len("Args:"):].strip()
                break
        out[name] = (short, first_args)
    return out


def md_escape(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ").strip()


def main() -> int:
    aggr = parse_aggressor(CNA)
    bofs_by_phase: dict[str, list[Bof]] = {}

    for phase_dir, _label in PHASES:
        pdir = ROOT / phase_dir
        if not pdir.is_dir():
            continue
        for crate_dir in sorted(pdir.iterdir()):
            if not crate_dir.is_dir():
                continue
            bof = parse_bof(phase_dir, crate_dir)
            if not bof:
                continue
            if bof.name in aggr:
                bof.aggr_short, bof.aggr_args = aggr[bof.name]
            bofs_by_phase.setdefault(phase_dir, []).append(bof)

    total = sum(len(v) for v in bofs_by_phase.values())

    lines: list[str] = []
    lines.append("# BOF Catalog\n")
    lines.append(
        "Auto-generated by `scripts/gen_bof_catalog.py`. Do not hand-edit.\n"
        "Regenerate after adding or modifying any BOF:\n\n"
        "```bash\npython3 scripts/gen_bof_catalog.py\n```\n"
    )
    lines.append(f"**Total BOFs**: {total}\n")
    lines.append("**Loader**: Cobalt Strike `inline-execute` or via `aggressor/dani-suite.cna` aliases.\n")
    lines.append(
        "**OPSEC posture**: every BOF declares its MITRE ATT&CK technique(s) at "
        "compile time, resolves all Win32 symbols via djb2 hashing, and encrypts "
        "string literals with `obfstr` so the resulting `.o` has no plaintext "
        "API names or strings. See [`mitre-mapping.md`](mitre-mapping.md) for the "
        "tactic-grouped index.\n"
    )

    lines.append("## Table of contents\n")
    for phase_dir, label in PHASES:
        if phase_dir not in bofs_by_phase:
            continue
        count = len(bofs_by_phase[phase_dir])
        anchor = label.lower().replace(" ", "-")
        lines.append(f"- [{label} ({count})](#{anchor})")
    lines.append("")

    for phase_dir, label in PHASES:
        items = bofs_by_phase.get(phase_dir, [])
        if not items:
            continue
        lines.append(f"## {label}\n")
        lines.append("| BOF | MITRE | Tactic | Description | Args |")
        lines.append("|:--|:--|:--|:--|:--|")
        for bof in items:
            mitre = ", ".join(t[0] for t in bof.techniques) or "—"
            tactic = " / ".join(sorted({t[2] for t in bof.techniques})) or "—"
            desc = bof.desc or bof.aggr_short or "(no description)"
            args = bof.aggr_args or "none"
            lines.append(
                f"| `{bof.name}` | {md_escape(mitre)} | {md_escape(tactic)} "
                f"| {md_escape(desc)} | {md_escape(args)} |"
            )
        lines.append("")

    lines.append("---\n")
    lines.append("_Maintained by Dani <daniagungg@gmail.com>._")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} — {total} BOFs across {len(bofs_by_phase)} phases")
    return 0


if __name__ == "__main__":
    sys.exit(main())
